### ISSUE TITLE
Может отказаться от динамических разделов как это сделали на бегонии ?

### ISSUE THREAD

**Issue by Hadenix** [ArrowOS-Devices/android_device_xiaomi_mt6768-common#1]
https://github.com/PixelExperience-Devices/device_xiaomi_begonia/commit/5ea750985ede4798c3491a9c83221036dec8df5a

**Comment by surblazer** [comment]
1. Please use english language
2. begonia was launched WITHOUT dynamic partitions, they was retrofitted. It's not possible to just drop them.
